apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-producer-service
  labels:
    run: rabbitmq-producer
  # annotations:
  #   dapr.io/enabled: "true"
  #   dapr.io/app-id: "rabbitmq-producer-service"
  #   dapr.io/app-port: "80"
  #   dapr.io/config: "tracing"
spec:
  type: LoadBalancer
  # type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http-port
      protocol: TCP
  selector:
    run: rabbitmq-producer    
