#FROM microsoft/aspnetcore-build AS build-env
FROM microsoft/dotnet:2.1.300-sdk  AS build-env

WORKDIR /app

COPY TechTalksMQProducer /TechTalksMQProducer/
COPY TechTalksModel /TechTalksModel/

# COPY NuGet.config ./

WORKDIR /TechTalksMQProducer
RUN dotnet restore

#COPY . ./

RUN dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image
#FROM microsoft/aspnetcore
FROM microsoft/dotnet:2.1.0-aspnetcore-runtime

WORKDIR /TechTalksMQProducer

COPY --from=build-env /TechTalksMQProducer/releaseOutput ./

#run the container as non-root user
USER 1000

ENTRYPOINT ["dotnet", "TechTalksMQProducer.dll"]
