#FROM microsoft/dotnet:2.1.300-sdk  AS build-env
FROM mcr.microsoft.com/dotnet/core/sdk:3.0  AS build-env


WORKDIR /app

COPY TechTalksMQProducer /TechTalksMQProducer/
COPY TechTalksModel /TechTalksModel/

# COPY NuGet.config ./

WORKDIR /TechTalksMQProducer
RUN dotnet restore

#COPY . ./

RUN dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image
#FROM microsoft/dotnet:2.1.0-aspnetcore-runtime
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0


WORKDIR /TechTalksMQProducer

COPY --from=build-env /TechTalksMQProducer/releaseOutput ./

#run the container as non-root user
USER 1000

ENTRYPOINT ["dotnet", "TechTalksMQProducer.dll"]
